const DraftData = [
    {
        date : "Jan 22, 11:05",
        source : "Upload",
        file: "Q4_Bank_Stmt_Final.csv",
        items : "3",
        status: "High",
    },
     {
        date : "Jan 22, 11:05",
        source : "Upload" ,
        file: "Q4_Bank_Stmt_Final.csv",
        items : "5",
        status: "Medium",
    },
     {
        date : "Jan 22, 11:05",
        source : "QuickBook",
        file: "Q4_Bank_Stmt_Final.csv",
        items : "12",
        status: "Medium",
    },
     {
        date : "Jan 22, 11:05",
        source : "Upload",
        file: "Q4_Bank_Stmt_Final.csv",
        items : "9",
        status: "Low",
    },
     {
        date : "Jan 22, 11:05",
        source : "QuickBook",
        file: "Q4_Bank_Stmt_Final.csv",
        items : "14",
        status: "High",
    },
    {
        date : "Jan 22, 11:05",
        source : "Upload",
        file: "Q4_Bank_Stmt_Final.csv",
        items : "3",
        status: "High",
    },
     {
        date : "Jan 22, 11:05",
        source : "Upload" ,
        file: "Q4_Bank_Stmt_Final.csv",
        items : "5",
        status: "Medium",
    },
     {
        date : "Jan 22, 11:05",
        source : "QuickBook",
        file: "Q4_Bank_Stmt_Final.csv",
        items : "12",
        status: "Medium",
    },
     {
        date : "Jan 22, 11:05",
        source : "Upload",
        file: "Q4_Bank_Stmt_Final.csv",
        items : "9",
        status: "Low",
    },
     {
        date : "Jan 22, 11:05",
        source : "QuickBook",
        file: "Q4_Bank_Stmt_Final.csv",
        items : "14",
        status: "High",
    },
    {
        date : "Jan 22, 11:05",
        source : "Upload",
        file: "Q4_Bank_Stmt_Final.csv",
        items : "3",
        status: "High",
    },
     {
        date : "Jan 22, 11:05",
        source : "Upload" ,
        file: "Q4_Bank_Stmt_Final.csv",
        items : "5",
        status: "Medium",
    },
     {
        date : "Jan 22, 11:05",
        source : "QuickBook",
        file: "Q4_Bank_Stmt_Final.csv",
        items : "12",
        status: "Medium",
    },
     {
        date : "Jan 22, 11:05",
        source : "Upload",
        file: "Q4_Bank_Stmt_Final.csv",
        items : "9",
        status: "Low",
    },
     {
        date : "Jan 22, 11:05",
        source : "QuickBook",
        file: "Q4_Bank_Stmt_Final.csv",
        items : "14",
        status: "High",
    },
]

export default DraftData;